### ISSUE TITLE
[Bug] 6.18 to some bugs

### ISSUE THREAD

**Issue by Night-GUA** [MyDragonBreath/AmongUs.MultiClientInstancing#25]
[Error  :Il2CppInterop] During invoking native->managed trampoline
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at MCI.Utils.CreatePlayerInstance(String name, Int32 id) in D:\zhuomian\code\AmongUs.MultiClientInstancing\MCI\Utils.cs:line 35
   at MCI.Patches.Keyboard_Joystick.Postfix() in D:\zhuomian\code\AmongUs.MultiClientInstancing\MCI\Patches\KeyboardJoystick.cs:line 19
   at DMD<KeyboardJoystick::Update>(KeyboardJoystick this)
   at (il2cpp -> managed) Update(IntPtr , Il2CppMethodInfo* )

**Comment by Night-GUA** [comment]
I am sorry,I clone another version...
